apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: slack-codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slack-codelab
    spec:
      containers:
      - name: master
        image: gcr.io/slackbot-212201/slack-vmworld:v1  # Replace PROJECT_ID
                                                   # with your project ID.
        ports:
          - containerPort: 443
        volumeMounts:
        - name: slack-token
          mountPath: /etc/slack-token
        env:
        - name: slack_token_path
          value: /etc/slack-token/slack-token
      volumes:
      - name: slack-token
        secret:
          secretName: slack-token  