apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: slack-codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slack-codelab
    spec:
      containers:
      - name: master
        image: gcr.io/slackbot-212201/slack-vmworld:v1  # Replace PROJECT_ID
                                                   # with your project ID.
        ports:
          - containerPort: 443
